import Head from 'next/head';

import BottomNavBar from '@/components/Layout/BottomNavBar';
import ThemeSelector from '@/components/General/ThemeSelector';
import TranslationSelector from '@/components/General/TranslationSelector';

export default function Layout({ title = 'miduweather', children }) {
  return (
    <div className='mx-auto flex h-screen w-screen flex-col items-center justify-center space-y-8 rounded-3xl bg-gray-800'>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ThemeSelector />
      <TranslationSelector />
      {children}
      {/* <BottomNavBar /> */}
    </div>
  );
}
