import Head from 'next/head';

import BottomNavBar from '@/components/Layout/BottomNavBar';

export default function Layout({ title = 'miduweather', children }) {
  return (
    <div className='mx-auto flex flex-col h-screen w-screen items-center justify-center space-y-8 rounded-3xl bg-gray-800 md:w-1/2'>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {children}
      <BottomNavBar />
    </div>
  );
}
