import { useContext } from 'react';

import Head from 'next/head';

import BottomNavBar from '@/components/Layout/BottomNavBar';
import ThemeSelector from '@/components/General/ThemeSelector';
import TranslationSelector from '@/components/General/TranslationSelector';
import TemperatureUnitSelector from '@/components/General/TemperatureUnitSelector';

import SettingsContext from '@/contexts/SettingsContext';

export default function Layout({ title = 'miduweather', children }) {
  const { theme } = useContext(SettingsContext);

  return (
    <div
      className={`mx-auto flex h-screen w-screen flex-col items-center justify-center space-y-8 rounded-3xl ${
        theme === 'light'
          ? 'bg-gradient-to-r from-green-300 via-blue-500 to-purple-600'
          : 'bg-gradient-to-r from-gray-700 via-gray-900 to-black'
      }`}
    >
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex h-12 w-full flex-row items-center justify-end space-x-4 px-8'>
        <ThemeSelector />
        <TranslationSelector />
        <TemperatureUnitSelector />
      </div>
      {children}
      {/* <BottomNavBar /> */}
    </div>
  );
}
