import Head from 'next/head';

import TodayCard from '@/components/TodayCard';
import ForecastCard from '@/components/ForecastCard';

export default function Index2({ weatherData }) {
  const { location, current, forecast } = weatherData;

  return (
    <div className='h-screen w-screen space-y-8 rounded-3xl bg-gray-800'>
      <Head>
        <title>miduweather</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-md text-center text-white'>
        midu<span className='font-bold'>weather</span>
      </h1>
      <TodayCard
        todayWeatherData={current}
        todayLocationData={location}
        todayForecast={forecast.forecastday[0]}
        tomorrowForecast={forecast.forecastday[1]}
      />
      {forecast.forecastday.map((forecast, index) => {
        if (index > 0) {
          return <ForecastCard key={index} forecast={forecast} />;
        }
      })}
    </div>
  );
}

export async function getServerSideProps(context) {
  const weatherData = require('../forecast.sample.json');

  return {
    props: {
      weatherData,
    },
  };
}
